// src/constants/languages.js

export const LANGUAGE_OPTIONS = [
  // 🌐 Indian Languages
  { label: 'Tamil', value: 'tamil' },
  { label: 'Telugu', value: 'telugu' },
  { label: 'Malayalam', value: 'malayalam' },
  { label: 'Kannada', value: 'kannada' },
  { label: 'Hindi', value: 'hindi' },
  { label: 'Bengali', value: 'bengali' },
  { label: 'Marathi', value: 'marathi' },
  { label: 'Gujarati', value: 'gujarati' },
  { label: 'Punjabi', value: 'punjabi' },
  { label: 'Odia', value: 'odia' },
  { label: 'Urdu', value: 'urdu' },
  { label: 'Sanskrit', value: 'sanskrit' },

  // 🌍 Major Global Languages
//   { label: 'English', value: 'english' },
//   { label: 'Spanish', value: 'spanish' },
//   { label: 'French', value: 'french' },
//   { label: 'German', value: 'german' },
//   { label: 'Italian', value: 'italian' },
//   { label: 'Portuguese', value: 'portuguese' },
//   { label: 'Russian', value: 'russian' },
//   { label: 'Chinese (Mandarin)', value: 'chinese' },
//   { label: 'Japanese', value: 'japanese' },
//   { label: 'Korean', value: 'korean' },
//   { label: 'Arabic', value: 'arabic' },
//   { label: 'Turkish', value: 'turkish' },
//   { label: 'Persian (Farsi)', value: 'persian' },
//   { label: 'Hebrew', value: 'hebrew' },
//   { label: 'Thai', value: 'thai' },
//   { label: 'Vietnamese', value: 'vietnamese' },
//   { label: 'Indonesian', value: 'indonesian' },
//   { label: 'Filipino (Tagalog)', value: 'filipino' },
//   { label: 'Malay', value: 'malay' },
//   { label: 'Swahili', value: 'swahili' },
//   { label: 'Dutch', value: 'dutch' },
//   { label: 'Greek', value: 'greek' },
//   { label: 'Polish', value: 'polish' },
//   { label: 'Swedish', value: 'swedish' },
//   { label: 'Norwegian', value: 'norwegian' },
//   { label: 'Finnish', value: 'finnish' },
//   { label: 'Danish', value: 'danish' },
//   { label: 'Czech', value: 'czech' },
//   { label: 'Hungarian', value: 'hungarian' },
//   { label: 'Romanian', value: 'romanian' },
//   { label: 'Ukrainian', value: 'ukrainian' },
//   { label: 'Bulgarian', value: 'bulgarian' },
//   { label: 'Serbian', value: 'serbian' },
//   { label: 'Croatian', value: 'croatian' },
//   { label: 'Slovak', value: 'slovak' },
//   { label: 'Slovenian', value: 'slovenian' },
//   { label: 'Latvian', value: 'latvian' },
//   { label: 'Lithuanian', value: 'lithuanian' },
//   { label: 'Estonian', value: 'estonian' },
//   { label: 'Icelandic', value: 'icelandic' },
//   { label: 'Irish', value: 'irish' },
//   { label: 'Welsh', value: 'welsh' },
//   { label: 'Scottish Gaelic', value: 'scottish_gaelic' },
//   { label: 'Albanian', value: 'albanian' },
//   { label: 'Bosnian', value: 'bosnian' },
//   { label: 'Macedonian', value: 'macedonian' },
//   { label: 'Armenian', value: 'armenian' },
//   { label: 'Georgian', value: 'georgian' },
//   { label: 'Kazakh', value: 'kazakh' },
//   { label: 'Uzbek', value: 'uzbek' },
//   { label: 'Turkmen', value: 'turkmen' },
//   { label: 'Tajik', value: 'tajik' },
//   { label: 'Nepali', value: 'nepali' },
//   { label: 'Sinhala', value: 'sinhala' },
//   { label: 'Burmese', value: 'burmese' },
//   { label: 'Khmer', value: 'khmer' },
//   { label: 'Lao', value: 'lao' },
//   { label: 'Mongolian', value: 'mongolian' },
//   { label: 'Pashto', value: 'pashto' },
//   { label: 'Somali', value: 'somali' },
//   { label: 'Amharic', value: 'amharic' },
//   { label: 'Yoruba', value: 'yoruba' },
//   { label: 'Hausa', value: 'hausa' },
//   { label: 'Zulu', value: 'zulu' },
//   { label: 'Afrikaans', value: 'afrikaans' },
//   { label: 'Maori', value: 'maori' },
//   { label: 'Samoan', value: 'samoan' },
//   { label: 'Tongan', value: 'tongan' },
//   { label: 'Fijian', value: 'fijian' },
];
