export const defaultFilters = {
  locations: [],
  propertyTypes: [],
  bhk: [],
  purpose: [],
  furnishing: [],
  possessionStatus: [],
  parking: [],
  facing: [],
  minBudget: 0,
  maxBudget: 10000000,
  swimmingPool: false,
  gatedCommunity: false,
  petsAllowed: false,
  ownership: [],
  amenities: [],
  appliances: [],
  bathroomFeatures: {
    jacuzzi: false,
    bathtubs: false,
    heatedFlooring: false,
  },
  plotDimensions: { length: 0, width: 0 },
  ageOfProperty: "",
  interiors: [],
};