export const chennaiAppData = [
  {
    id: -5,
    Company: "Chennai One (CUMTA)",
    EventsCalendarTitle:
      "All-in-one app for Chennai buses, metro, and train ticketing.",
    EventsCalendarContent: "Sharul Channa – Sareeously Not Sorry.",
    EventsCalendarMonth: "26 July",
    EventsCalendarTime: "07:00 PM",
    EventsCalendarCategory: "Comedy Shows",
    image: "/images/chennai-app-images/chennai-one-app.jpg",
    image1: "/images/NewsLetter/Times of india.jpeg",
    link: "/events",
    location: "Punch - Unpaid Therapist: Chennai",
    language: "English",
    hours: "1 hour 15 minutes",
    ageLimit: "3 years +",
    rleigion: "Comedy",
    aboutFull: `A Brand-New Stand-Up Comedy Special ...`,
    popupContent: [
      <>Unified QR ticketing</>,
      <>Journey planner with shortest routes</>,
      <>Real-time metro & bus tracking</>,
      <>Wallet recharge & payments</>,
      <>Single app for bus, metro, train, taxi</>,
      <>Multilingual interface</>,
    ],
  },

  {
    id: -6,
    Company: "The Hindu",
    EventsCalendarTitle: "Pragg has been amazing this year....",
    EventsCalendarContent: "Sharul Channa – Sareeously Not Sorry.",
    EventsCalendarMonth: "26 July",
    EventsCalendarTime: "07:00 PM",
    EventsCalendarCategory: "Comedy Shows",
    image: "/images/NewsLetter/The hindu.jpeg",
    image1: "/images/NewsLetter/The hindu.jpeg",
    link: "/events",
    location: "Punch - Unpaid Therapist: Chennai",
    language: "English",
    hours: "1 hour 15 minutes",
    ageLimit: "3 years +",
    rleigion: "Comedy",
    aboutFull: `A Brand-New Stand-Up Comedy Special ...`,
  },
  {
    id: -6,
    Company: "The Hindu",
    EventsCalendarTitle: "Pragg has been amazing this year....",
    EventsCalendarContent: "Sharul Channa – Sareeously Not Sorry.",
    EventsCalendarMonth: "26 July",
    EventsCalendarTime: "07:00 PM",
    EventsCalendarCategory: "Comedy Shows",
    image: "/images/NewsLetter/The hindu.jpeg",
    image1: "/images/NewsLetter/The hindu.jpeg",
    link: "/events",
    location: "Punch - Unpaid Therapist: Chennai",
    language: "English",
    hours: "1 hour 15 minutes",
    ageLimit: "3 years +",
    rleigion: "Comedy",
    aboutFull: `A Brand-New Stand-Up Comedy Special ...`,
  },
];
