export const propertiesData = [
  {
    id: 1,
    name: "Shivananda Flats",
    title: "2 BHK Flat in Pallavaram, Chennai",
    price: "₹65 Lac",
    sqftPrice: "₹5,000 /sqft",
    size: "1,300 sqft",
    areaLabel: "Built-up Area",
    type: "Residential Apartment",
    propertyCategory: "Flat / Apartments",
    bhk: "2 BHK",
    availableFor: "Family",
    location: "Pallavaram",
    status: "Ready To Move",
    amenities: ["Parking", "Lift", "Park"],
    description:
      "Spacious 2 BHK flat with modern interiors and balcony, located in Pallavaram with easy access to schools and metro.",
    image:
      "https://imagecdn.99acres.com/media1/32526/12/650532437M-1758453715074.jpg",
    uploaded: "2mo ago",
    owner: "Owner",
  },
  {
    id: 2,
    name: "Skyline Residency",
    title: "3 BHK Residential Apartment in OMR",
    price: "₹86 Lac",
    sqftPrice: "₹4,800 /sqft",
    size: "1,800 sqft",
    areaLabel: "Super Built-up Area",
    type: "Residential Apartment",
    propertyCategory: "Flat / Apartments",
    bhk: "3 BHK",
    availableFor: "Family",
    location: "OMR",
    status: "Ready To Move",
    amenities: ["Parking", "Lift", "Power Backups", "Gym"],
    description:
      "Luxury 3 BHK apartment with covered parking, power backup, and gym facilities in a gated community on OMR.",
    image:
      "https://imagecdn.99acres.com/media1/32525/15/650532431M-1758453715074.jpg",
    uploaded: "1mo ago",
    owner: "Agent",
  },
  {
    id: 3,
    name: "Greenwoods Villa",
    title: "4 BHK Independent Villa in ECR",
    price: "₹1.8 Cr",
    sqftPrice: "₹6,200 /sqft",
    size: "2,900 sqft",
    areaLabel: "Carpet Area",
    type: "Independent House/Villa",
    propertyCategory: "Villa",
    bhk: "4 BHK",
    availableFor: "Family",
    location: "ECR",
    status: "Ready To Move",
    amenities: ["Parking", "Park", "Power Backups"],
    description:
      "Spacious 4 BHK villa with private garden, large living space, and ocean breeze, located close to ECR beach.",
    image:
      "https://imagecdn.99acres.com/media1/32526/22/650532447M-1758453715074.jpg",
    uploaded: "3w ago",
    owner: "Builder",
  },
  {
    id: 4,
    name: "Urban Nest",
    title: "1 BHK Studio Apartment in Padur",
    price: "₹32 Lac",
    sqftPrice: "₹4,000 /sqft",
    size: "800 sqft",
    areaLabel: "Super Built-up Area",
    type: "Serviced Apartments",
    propertyCategory: "Serviced Apartments",
    bhk: "1 BHK",
    availableFor: "Single Men",
    location: "Padur",
    status: "Under Construction",
    amenities: ["Lift", "Gym"],
    description:
      "Affordable studio apartment ideal for professionals with gym and lift facilities in Padur.",
    image:
      "https://imagecdn.99acres.com/media1/32526/42/650532467M-1758453715074.jpg",
    uploaded: "5d ago",
    owner: "Owner",
  },
  {
    id: 5,
    name: "Sunrise Villas",
    title: "3 BHK Independent Villa in OMR",
    price: "₹1.1 Cr",
    sqftPrice: "₹5,600 /sqft",
    size: "2,000 sqft",
    areaLabel: "Built-up Area",
    type: "Independent House/Villa",
    propertyCategory: "Villa",
    bhk: "3 BHK",
    availableFor: "Family",
    location: "OMR",
    status: "Ready To Move",
    amenities: ["Parking", "Park", "Power Backups"],
    description:
      "Independent 3 BHK villa with garden and spacious living room in a peaceful OMR community.",
    image:
      "https://imagecdn.99acres.com/media1/32526/56/650532476M-1758453715074.jpg",
    uploaded: "4w ago",
    owner: "Agent",
  },
  {
    id: 6,
    name: "Royal Heights",
    title: "2 BHK Builder Floor in Pallavaram",
    price: "₹58 Lac",
    sqftPrice: "₹4,600 /sqft",
    size: "1,250 sqft",
    areaLabel: "Built-up Area",
    type: "Independent/Builder Floor",
    propertyCategory: "Builder Floor",
    bhk: "2 BHK",
    availableFor: "Single Women",
    location: "Pallavaram",
    status: "Ready To Move",
    amenities: ["Lift", "Power Backups"],
    description:
      "Beautiful 2 BHK builder floor with excellent ventilation and lift access near Pallavaram bus terminus.",
    image:
      "https://imagecdn.99acres.com/media1/32526/82/650532498M-1758453715074.jpg",
    uploaded: "2mo ago",
    owner: "Owner",
  },
  {
    id: 7,
    name: "Park View Residences",
    title: "5 BHK Farm House in ECR",
    price: "₹2.5 Cr",
    sqftPrice: "₹7,500 /sqft",
    size: "3,300 sqft",
    areaLabel: "Plot Area",
    type: "Farm House",
    propertyCategory: "Farm House",
    bhk: "5 BHK",
    availableFor: "Tenants with Company",
    location: "ECR",
    status: "Ready To Move",
    amenities: ["Parking", "Park", "Power Backups"],
    description:
      "Sprawling 5 BHK farmhouse surrounded by lush greenery, perfect for corporate rentals or family retreats.",
    image:
      "https://imagecdn.99acres.com/media1/32527/02/650532507M-1758453715074.jpg",
    uploaded: "1w ago",
    owner: "Builder",
  },
  {
    id: 8,
    name: "Elite Enclave",
    title: "2 BHK Residential Apartment in Padur",
    price: "₹72 Lac",
    sqftPrice: "₹4,900 /sqft",
    size: "1,450 sqft",
    areaLabel: "Built-up Area",
    type: "Residential Apartment",
    propertyCategory: "Flat / Apartments",
    bhk: "2 BHK",
    availableFor: "Family",
    location: "Padur",
    status: "Ready To Move",
    amenities: ["Parking", "Lift", "Gym"],
    description:
      "Well-ventilated apartment with modern kitchen, power backup, and kids' play area in Padur.",
    image:
      "https://imagecdn.99acres.com/media1/32527/16/650532514M-1758453715074.jpg",
    uploaded: "3w ago",
    owner: "Owner",
  },
  {
    id: 9,
    name: "Lakefront Bliss",
    title: "3 BHK Independent Villa in Pallavaram",
    price: "₹1.3 Cr",
    sqftPrice: "₹5,800 /sqft",
    size: "2,250 sqft",
    areaLabel: "Carpet Area",
    type: "Independent House/Villa",
    propertyCategory: "Villa",
    bhk: "3 BHK",
    availableFor: "Family",
    location: "Pallavaram",
    status: "Ready To Move",
    amenities: ["Parking", "Park"],
    description:
      "Gorgeous lake-view villa with garden, parking, and modern design located in Pallavaram.",
    image:
      "https://imagecdn.99acres.com/media1/32527/35/650532531M-1758453715074.jpg",
    uploaded: "2w ago",
    owner: "Owner",
  },
  {
    id: 10,
    name: "Metro Edge Apartments",
    title: "2 BHK Serviced Apartment in OMR",
    price: "₹60 Lac",
    sqftPrice: "₹4,700 /sqft",
    size: "1,280 sqft",
    areaLabel: "Built-up Area",
    type: "Serviced Apartments",
    propertyCategory: "Serviced Apartments",
    bhk: "2 BHK",
    availableFor: "Single Women",
    location: "Thiruvottiyur",
    status: "Under Construction",
    amenities: ["Lift", "Power Backups", "Gym"],
    description:
      "Premium 2 BHK serviced apartment near metro connectivity with lift and gym facilities.",
    image:
      "https://imagecdn.99acres.com/media1/32527/52/650532547M-1758453715074.jpg",
    uploaded: "6d ago",
    owner: "Builder",
  },
  {
    id: 11,
    name: "Veedu Home",
    title: "2 BHK Serviced Apartment in OMR",
    price: "₹60 Lac",
    sqftPrice: "₹4,700 /sqft",
    size: "1,280 sqft",
    areaLabel: "Built-up Area",
    type: "Vadakai Veedu",
    propertyCategory: "Serviced Apartments",
    bhk: "2 BHK",
    availableFor: "Single Women",
    location: "OMR",
    status: "Under Construction",
    amenities: ["Lift", "Power Backups", "Gym"],
    description:
      "Premium 2 BHK serviced apartment near metro connectivity with lift and gym facilities.",
    image:
      "https://imagecdn.99acres.com/media1/32527/52/650532547M-1758453715074.jpg",
    uploaded: "6d ago",
    owner: "Builder",
  },
];

// Generate unique filter options
const bhkOptions = [...new Set(propertiesData.map((p) => p.bhk))];
const typeOptions = [...new Set(propertiesData.map((p) => p.type))];
const availableForOptions = [
  ...new Set(propertiesData.map((p) => p.availableFor)),
];
const locationOptions = [...new Set(propertiesData.map((p) => p.location))];
const amenitiesOptions = [
  ...new Set(propertiesData.flatMap((p) => p.amenities)), // flatten all arrays
];

export const options = {
  bhkOptions,
  typeOptions,
  availableForOptions,
  locationOptions,
  amenitiesOptions,
};
